#!/usr/bin/env php
<?php
/**
 * Copyright 2015 github.com/noahheck
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Executes the E_PDOStatement PHPUnit test suite
 *
 * Allows easy specification of common test suite parameters to provide an easier way to run the tests
 *
 * @package 	E_PDOStatement
 * @since 		2015-10-24
 */

chdir(dirname(__FILE__));

$report 		= "";

$argWphp 		= "";
$argWTestPhp 	= "";

$numArgs 		= $argc;
$curArg 		= 0;

$lastArg 		= false;

foreach ($argv as $arg)
{
	$curArg++;

	// Skip the first arg; it will always be the name of this script
	if ($curArg === 1)
	{
		continue;
	}

	if ($arg == "--help")
	{
		$scriptName = basename(__FILE__, ".php");
		echo <<<EOH
E_PDOStatement PHPUnit Test Suite Runner

Usage:  $scriptName [Options]

Options:
    --report     Generate html code coverage report in coverage directory


Miscellaneous Options:
    --help      Display this help and exit

EOH;
		exit;
	}

	if ($arg == "--report")
	{
		$report = "--coverage-html coverage";
		continue;
	}

	echo "
Unknown argument: {$arg}

Exiting...

";
	exit;
}

passthru("../vendor/bin/phpunit --colors=always {$report} ./");
